services:
  - type: web
    name: ustad-ai-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run prebuild && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: ustad-ai-client
    runtime: node
    rootDir: client
    buildCommand: npm install && npm run prebuild && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        syncFromCustomerDB: false
